version: '3.8'

services:
  bot:
    container_name: bot
    build: .
  db:
    container_name: db
    ports:
      - '5432'
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

volumes:
  pg_data:
