from aiogram.dispatcher.filters.state import StatesGroup, State


class StartState(StatesGroup):
    rules = State()
    rules_for_refilling = State()
    rule_decision = State()
    confidential_decision = State()
    user_name = State()
    gender = State()
    photo = State()
    email = State()
    decision_about_photo = State()
    upload_photo = State()
    gitlab = State()
    department = State()
    design = State()
    get_skills_design = State()
    get_skills_dev = State()
    get_city = State()
    get_source = State()
    expectations = State()
    development_vector = State()

    time_for_work = State()
    education = State()
    management_wish = State()

    finish_questions = State()
    check_questionnaire = State()
    update_info = State()
    choice = State()
    get_moder = State()
    send_teamleads = State()
    send_instructions = State()
    adaptaion_chat = State()
    friday_meetings = State()
    check_membership = State()
    cycle = State()
